# docker-compose.yml
version: '2.4'
services:
  deephealth-ui:
    mem_limit: 4548m
    image: deephealth-ui:latest
    container_name: deephealth-ui
    build: ./
    expose:
      - 4200
    ports:
      - 4200:4200
    restart: unless-stopped
    environment:
        - JAVA_OPTS="-Xmx4548m -Xss512k"
    volumes:
      - ./config.json:/src/assets/config.json
